// Pre-written game themes — no AI needed
// Space type distribution (same for all themes):
// card (lucky):  3,12,17,21,25,30,34
// trap (bad):    6,14,19,23,28,32,35
// bonus:         9,27
// win:           36
// normal:        all others

const s = (id, type, name, icon) => ({ id, type, name, icon });

export const THEMES = [
  {
    id: "medieval",
    label: "🏰 פנטזיה ימי-ביניימית",
    title: "מסע המלכות",
    subtitle: "הרפתקה ימי-ביניימית",
    icon: "🏰",
    spaces: [
      s(1,"normal","שער הכפר","🏠"), s(2,"normal","שביל היער","🌲"),
      s(3,"card","ברכת הנזיר","✨"), s(4,"normal","נהר הגבול","🌊"),
      s(5,"normal","גשר האבן","🌉"), s(6,"trap","מארב השודדים","🗡️"),
      s(7,"normal","שדות החיטה","🌾"), s(8,"normal","כפר הדייגים","🎣"),
      s(9,"bonus","קפיצת הרוח","💨"), s(10,"normal","מגדל השמירה","🗼"),
      s(11,"normal","האכסניה","🍺"), s(12,"card","אוצר הנסיך","💰"),
      s(13,"normal","שוק הכפר","🏪"), s(14,"trap","בוץ הביצה","🐸"),
      s(15,"normal","יער האלונים","🌳"), s(16,"normal","מחנה הלוחמים","⚔️"),
      s(17,"card","עזרת האלפים","🧝"), s(18,"normal","שביל ההרים","🏔️"),
      s(19,"trap","מפולת אבנים","🪨"), s(20,"normal","מעבר הדרקון","🐉"),
      s(21,"card","ברכת האצילים","👑"), s(22,"normal","המערה הסודית","🕯️"),
      s(23,"trap","מלכודת הארס","☠️"), s(24,"normal","גן המלך","🌺"),
      s(25,"card","נס ממרומים","🌟"), s(26,"normal","שער הטירה","🚪"),
      s(27,"bonus","רוח גבית","🌠"), s(28,"trap","כישוף האפלה","🧙"),
      s(29,"normal","חצר הטירה","🏰"), s(30,"card","חסות המלך","🛡️"),
      s(31,"normal","מגדל הפעמונים","🔔"), s(32,"trap","שומר הצל","👹"),
      s(33,"normal","גרם המדרגות","🪜"), s(34,"card","חד-הקרן","🦄"),
      s(35,"trap","שומר הכניסה","💀"), s(36,"win","כס המלכות","🏆"),
    ],
    events: {
      card: [
        { title:"ברכת הנזיר", description:"נזיר קדוש בירך אותך בדרכך. המזל חייך לך!", icon:"🙏", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
        { title:"אוצר נסתר", description:"מצאת ארגז אוצרות נסתר על שביל עלום. התקדם!", icon:"💰", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
        { title:"עזרת האלף", description:"אלף מהיער הקסום הראה לך קיצור דרך מפתיע.", icon:"🧝", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
        { title:"סוס מהיר", description:"סוחר נדיב נתן לך סוס מהיר להמשך הדרך.", icon:"🐎", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
        { title:"חסות המלך", description:"צו המלך נשלח אליך — הדרך פנויה לפניך!", icon:"👑", effectText:"התקדם 2 משבצות", effect:{type:"move",value:2} },
        { title:"חד-הקרן הקסום", description:"חד-קרן נדיר הופיע ונשא אותך על גבו קדימה!", icon:"🦄", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
        { title:"מפת הקיצור", description:"מצאת מפת אוצר עתיקה עם קיצור ישיר לטירה.", icon:"🗺️", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
      ],
      trap: [
        { title:"מארב שודדים", description:"שודדים קפצו מהשיחים! נאלצת לחזור לאחור.", icon:"🗡️", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"בוץ הביצה", description:"נפלת לתוך ביצה עמוקה. לוקח זמן לצאת.", icon:"🐸", effectText:"חזור 2 משבצות", effect:{type:"move",value:-2} },
        { title:"מפולת אבנים", description:"אבנים גדולות נפלו וחסמו את הדרך. נסוג!", icon:"🪨", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"כישוף האטה", description:"קוסמת אפלה הטילה עליך קסם האטה.", icon:"🧙", effectText:"חזור 2 משבצות", effect:{type:"move",value:-2} },
        { title:"שומר אכזרי", description:"שומר הטירה הגדול לא נתן לך לעבור. חזרה!", icon:"👹", effectText:"חזור 4 משבצות", effect:{type:"move",value:-4} },
        { title:"מלכודת ארס", description:"דרכת על מלכודת ארס שהכינו האויבים.", icon:"☠️", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"אבוד ביער", description:"איבדת את הדרך ביער האפל. נדדת לאחור.", icon:"🌑", effectText:"חזור 2 משבצות", effect:{type:"move",value:-2} },
      ],
      bonus: [
        { title:"קיצור דרך!", description:"גילית שביל נסתר שמוביל ישר קדימה בקפיצה!", icon:"💨", effectText:"התקדם 5 משבצות", effect:{type:"move",value:5} },
        { title:"רוח גבית!", description:"רוח קסומה נושאת אותך קדימה במהירות מסחררת!", icon:"🌠", effectText:"התקדם 5 משבצות", effect:{type:"move",value:5} },
      ],
    },
  },

  {
    id: "space",
    label: "🚀 שודדי חלל",
    title: "שודדי הגלקסיה",
    subtitle: "הרפתקה בין-גלקטית",
    icon: "🚀",
    spaces: [
      s(1,"normal","כרית ההשקה","🛸"), s(2,"normal","מסלול הלוויין","🛰️"),
      s(3,"card","שדה האסטרואידים הזהוב","💫"), s(4,"normal","תחנת הדלק","⛽"),
      s(5,"normal","ירח הקרח","🌙"), s(6,"trap","שדה המוקשים","💥"),
      s(7,"normal","נבולה הורודה","🌸"), s(8,"normal","תחנת החלל","🏗️"),
      s(9,"bonus","מנוע הוורפ","⚡"), s(10,"normal","כוכב הגמד","⭐"),
      s(11,"normal","ענן הגז","☁️"), s(12,"card","אוצר השודדים","🎁"),
      s(13,"normal","טבעות שבתאי","💍"), s(14,"trap","חור שחור קטן","🌀"),
      s(15,"normal","גלקסיה אחרת","🌌"), s(16,"normal","תחנת המסחר","🏪"),
      s(17,"card","ברית הרובוטים","🤖"), s(18,"normal","שביל הכוכבים","✨"),
      s(19,"trap","פגיעת מטאוריט","☄️"), s(20,"normal","פלנטה ירוקה","🌍"),
      s(21,"card","ממצא עתיק","🏺"), s(22,"normal","מסדרון האסטרואידים","🪨"),
      s(23,"trap","מלכודת מסלול","🕳️"), s(24,"normal","נמל החלל","🏙️"),
      s(25,"card","קוד החירום","📡"), s(26,"normal","שדה הקרב","💫"),
      s(27,"bonus","פורטל קוונטי","🌈"), s(28,"trap","שדה כוח אויב","⚠️"),
      s(29,"normal","פלנטת הקרח","🧊"), s(30,"card","ספינת האם","🛳️"),
      s(31,"normal","מסלול הסופי","🛤️"), s(32,"trap","לכידת חוצנים","👽"),
      s(33,"normal","שדה הפלזמה","🔥"), s(34,"card","ניצחון הגלקסיה","🌟"),
      s(35,"trap","מנוע תקוע","🔧"), s(36,"win","כוכב האוצר","🏆"),
    ],
    events: {
      card: [
        { title:"שדה אסטרואידים זהוב", description:"גילית אסטרואיד עמוס מינרלים נדירים. הדלק ממריא!", icon:"💫", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
        { title:"אות עזרה!", description:"ספינה ידידותית שלחה לך קואורדינטות קיצור.", icon:"📡", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
        { title:"ברית הרובוטים", description:"צי הרובוטים החליט לעזור לך — הדרך סלולה!", icon:"🤖", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
        { title:"ממצא עתיק", description:"מצאת מנוע חוצנים עתיק שמגביר את מהירותך.", icon:"🏺", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
        { title:"קוד גישה", description:"פרצת לבסיס האויב וגנבת מפת קיצור.", icon:"💻", effectText:"התקדם 2 משבצות", effect:{type:"move",value:2} },
        { title:"ספינת האם", description:"ספינת האם שלחה טיל מאיץ שדחף אותך קדימה.", icon:"🛳️", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
        { title:"ניצחון בקרב", description:"ניצחת את קרב הגלקסיה! הדרך לכוכב פתוחה.", icon:"🌟", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
      ],
      trap: [
        { title:"שדה מוקשים", description:"התפוצצות! ספינתך ניזוקה ונסוגה לאחור.", icon:"💥", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"חור שחור!", description:"כוח המשיכה של חור שחור שאב אותך לאחור.", icon:"🌀", effectText:"חזור 4 משבצות", effect:{type:"move",value:-4} },
        { title:"פגיעת מטאוריט", description:"מטאוריט פגע ישירות במנוע. חייבים לנסוג לתיקון.", icon:"☄️", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"מלכודת מסלול", description:"נפלת בפח! מסלול מזויף הוביל אותך לאחור.", icon:"🕳️", effectText:"חזור 2 משבצות", effect:{type:"move",value:-2} },
        { title:"לכידת חוצנים", description:"חוצנים עוינים לכדו אותך לחקירה קצרה.", icon:"👽", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"מנוע תקוע", description:"המנוע תקוע! הנדסאים מתקנים אבל זה לוקח זמן.", icon:"🔧", effectText:"חזור 2 משבצות", effect:{type:"move",value:-2} },
        { title:"שדה כוח אויב", description:"שדה הכוח של האויב הקפיץ אותך לאחור.", icon:"⚠️", effectText:"חזור 2 משבצות", effect:{type:"move",value:-2} },
      ],
      bonus: [
        { title:"פורטל קוונטי!", description:"מצאת פורטל קוונטי סודי — קפיצה ענקית קדימה!", icon:"🌈", effectText:"התקדם 5 משבצות", effect:{type:"move",value:5} },
        { title:"מנוע וורפ!", description:"מנוע הוורפ הופעל — מהירות אור לכיוון המטרה!", icon:"⚡", effectText:"התקדם 5 משבצות", effect:{type:"move",value:5} },
      ],
    },
  },

  {
    id: "ocean",
    label: "🌊 מסע תת-ימי",
    title: "מעמקי האוקיינוס",
    subtitle: "הרפתקה בתהום הים",
    icon: "🌊",
    spaces: [
      s(1,"normal","חוף הפנינים","🏖️"), s(2,"normal","שונית האלמוגים","🪸"),
      s(3,"card","פנינת הים","🦪"), s(4,"normal","יער האצות","🌿"),
      s(5,"normal","מערת הצבעים","🐠"), s(6,"trap","ישמעאל העקטופוס","🐙"),
      s(7,"normal","מרחב הסרדינים","🐟"), s(8,"normal","גן הצדפות","🐚"),
      s(9,"bonus","זרם החם","🌊"), s(10,"normal","סלע המיסתורין","🪨"),
      s(11,"normal","בועת האוויר","🫧"), s(12,"card","אוצר הספינה הטבועה","🏴‍☠️"),
      s(13,"normal","מדרון הים","🌋"), s(14,"trap","מדוזת הרעל","🪼"),
      s(15,"normal","מישור הים","🌊"), s(16,"normal","שרשרת האיים","🏝️"),
      s(17,"card","כוכב הים הקסום","⭐"), s(18,"normal","הרפתקת הלווייתן","🐋"),
      s(19,"trap","מלכודת הרשת","🕸️"), s(20,"normal","פסגת הרכס","⛰️"),
      s(21,"card","עזרת הדולפין","🐬"), s(22,"normal","מחצבת הספיר","💎"),
      s(23,"trap","סערת הים","⛈️"), s(24,"normal","מנהרת הזרם","🌀"),
      s(25,"card","מצא אוצר עתיק","🏺"), s(26,"normal","שומר השונית","🦈"),
      s(27,"bonus","מדחף הגל","🌊"), s(28,"trap","סחרור התהום","🌀"),
      s(29,"normal","ממלכת הצבי-ים","🦑"), s(30,"card","הגנת המלך-ים","🔱"),
      s(31,"normal","שביל המלחים","⚓"), s(32,"trap","מחסום הצוק","🪨"),
      s(33,"normal","ביצת המנגרובים","🌿"), s(34,"card","אי האוצרות","🏝️"),
      s(35,"trap","מפל הים","💧"), s(36,"win","ארמון הים","🏆"),
    ],
    events: {
      card: [
        { title:"פנינה נדירה", description:"מצאת פנינת ים נדירה! הגאות נושאת אותך קדימה.", icon:"🦪", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
        { title:"אוצר ספינה טבועה", description:"גילית ספינה טבועה עם מפה לקיצור הדרך!", icon:"🏴‍☠️", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
        { title:"עזרת הדולפין", description:"עדר דולפינים ידידותי קידם אותך בשמחה קדימה!", icon:"🐬", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
        { title:"זרם חם", description:"זרם חם ומהיר נשא את ספינתך קדימה.", icon:"🌊", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
        { title:"כוכב ים קסום", description:"כוכב ים זהוב הראה לך את הדרך הסודית.", icon:"⭐", effectText:"התקדם 2 משבצות", effect:{type:"move",value:2} },
        { title:"אוצר עתיק", description:"כלי ים עתיקים עם כוח הדחף המסתורי.", icon:"🏺", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
        { title:"הגנת המלך-ים", description:"מלך הים בירך אותך ושלח אותך קדימה בגאון!", icon:"🔱", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
      ],
      trap: [
        { title:"עקטופוס מסוכן", description:"עקטופוס ענק אחז בך ומשך אותך לאחור!", icon:"🐙", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"מדוזת רעל", description:"נגעת במדוזה רעילה! צריך לנוח ולהחלים.", icon:"🪼", effectText:"חזור 2 משבצות", effect:{type:"move",value:-2} },
        { title:"מלכודת רשת", description:"נתקלת ברשת ים ישנה שסיבכה אותך. נסוג!", icon:"🕸️", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"סערת ים", description:"סערה פתאומית זרקה אותך כמה משבצות לאחור.", icon:"⛈️", effectText:"חזור 4 משבצות", effect:{type:"move",value:-4} },
        { title:"סחרור התהום", description:"נפלת לתוך סחרור תת-ימי. יצאת רחוק לאחור.", icon:"🌀", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"מחסום צוק", description:"צוק חד חסם את הדרך. עברת לכיוון אחר.", icon:"🪨", effectText:"חזור 2 משבצות", effect:{type:"move",value:-2} },
        { title:"מפל ים", description:"מפל תת-ימי לקח אותך לאחור בבת אחת.", icon:"💧", effectText:"חזור 2 משבצות", effect:{type:"move",value:-2} },
      ],
      bonus: [
        { title:"זרם מהיר!", description:"מצאת את הזרם המהיר ביותר באוקיינוס — קדימה!", icon:"🌊", effectText:"התקדם 5 משבצות", effect:{type:"move",value:5} },
        { title:"מדחף הגלים!", description:"גל ענק שלח אותך מהר קדימה בגלישה מטורפת!", icon:"🏄", effectText:"התקדם 5 משבצות", effect:{type:"move",value:5} },
      ],
    },
  },

  {
    id: "volcano",
    label: "🌋 אי הרי-געש",
    title: "אי האש",
    subtitle: "שרידה על האי הבוער",
    icon: "🌋",
    spaces: [
      s(1,"normal","חוף ההגעה","🏖️"), s(2,"normal","שביל הבזלת","🪨"),
      s(3,"card","מעיין הרפואה","💧"), s(4,"normal","שדה הלבה הקפואה","⬛"),
      s(5,"normal","יער הטרופי","🌴"), s(6,"trap","התפרצות פתאומית","🌋"),
      s(7,"normal","כפר הילידים","🛖"), s(8,"normal","מרחב הציפורים","🦜"),
      s(9,"bonus","גשר הקפיצה","🌉"), s(10,"normal","שדה העשן","💨"),
      s(11,"normal","מפל האש","🔥"), s(12,"card","מתנת השמאן","🪄"),
      s(13,"normal","מדרון הבריחה","🏃"), s(14,"trap","שדה הלבה החמה","🌋"),
      s(15,"normal","מקלט הסלעים","🏔️"), s(16,"normal","גן הצמחים","🌿"),
      s(17,"card","עזרת הראש-שבט","👒"), s(18,"normal","הר המשנה","⛰️"),
      s(19,"trap","רעידת אדמה","💥"), s(20,"normal","ממלכת הקופים","🐒"),
      s(21,"card","גשם מרפא","🌧️"), s(22,"normal","הפסגה הראשונה","🗻"),
      s(23,"trap","עשן הרעיל","🌫️"), s(24,"normal","שביל הקוקוסים","🥥"),
      s(25,"card","שורש הקסם","🌱"), s(26,"normal","קדרות הסכנה","☁️"),
      s(27,"bonus","מסלול ההר","⛷️"), s(28,"trap","גחמת האש","🔥"),
      s(29,"normal","פתח המערה","🕳️"), s(30,"card","אוצר הגעש","💎"),
      s(31,"normal","הר הגעש הראשי","🌋"), s(32,"trap","עמוד האש","⚡"),
      s(33,"normal","שביל האחרון","🛤️"), s(34,"card","שמן הגעש","🫙"),
      s(35,"trap","התפרצות סופית","💥"), s(36,"win","פסגת ההצלה","🏆"),
    ],
    events: {
      card: [
        { title:"מעיין רפואי", description:"מצאת מעיין מרפא! כוחות מתחדשים, קדם!", icon:"💧", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
        { title:"מתנת השמאן", description:"שמאן חכם נתן לך כישוף ריצה מהירה.", icon:"🪄", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
        { title:"עזרת הראש-שבט", description:"ראש השבט הכיר בך כגיבור ושלח מדריך.", icon:"👒", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
        { title:"גשם מרפא", description:"גשם קצר רענן אותך ואיפשר לך לרוץ מהר.", icon:"🌧️", effectText:"התקדם 2 משבצות", effect:{type:"move",value:2} },
        { title:"שורש הקסם", description:"שורש עתיק נתן לך כוח על-אנושי לרגע.", icon:"🌱", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
        { title:"אוצר הגעש", description:"אבן ייחודית מהגעש נתנה לך כוחות מיוחדים!", icon:"💎", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
        { title:"שמן הגעש", description:"שמן מיוחד מהלבה הפך אותך למהיר כברק.", icon:"🫙", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
      ],
      trap: [
        { title:"התפרצות!", description:"הר הגעש התפרץ! ברחת אחורה מהר מאוד.", icon:"🌋", effectText:"חזור 4 משבצות", effect:{type:"move",value:-4} },
        { title:"שדה לבה", description:"נתקלת בשדה לבה חמה שאי אפשר לעבור. עקיפה!", icon:"🔥", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"רעידת אדמה", description:"רעידת אדמה הפילה אותך לאחור. נאחזת!", icon:"💥", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"עשן רעיל", description:"נשמת עשן רעיל ואיבדת כיוון. נסוג!", icon:"🌫️", effectText:"חזור 2 משבצות", effect:{type:"move",value:-2} },
        { title:"גחמת האש", description:"לשון אש ענקית הכריחה אותך לסטות לאחור.", icon:"🔥", effectText:"חזור 2 משבצות", effect:{type:"move",value:-2} },
        { title:"עמוד האש", description:"עמוד אש ענק חסם את הדרך. עצרת ונסגת.", icon:"⚡", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"התפרצות סופית", description:"הר הגעש רעם — נאלצת לרוץ חזרה להתחבא!", icon:"💥", effectText:"חזור 4 משבצות", effect:{type:"move",value:-4} },
      ],
      bonus: [
        { title:"מסלול הר!", description:"מצאת מסלול קיצור מיוחד דרך ההר. קדמה!", icon:"⛷️", effectText:"התקדם 5 משבצות", effect:{type:"move",value:5} },
        { title:"גשר הקפיצה!", description:"גשר מתנודד אבל מהיר — קפצת לפני שנפל!", icon:"🌉", effectText:"התקדם 5 משבצות", effect:{type:"move",value:5} },
      ],
    },
  },

  {
    id: "wizards",
    label: "🧙 מכשפים וקסמים",
    title: "בית הספר לקסמים",
    subtitle: "הרפתקה קסומה",
    icon: "🧙",
    spaces: [
      s(1,"normal","שער הקסם","🚪"), s(2,"normal","המסדרון הראשי","🏛️"),
      s(3,"card","עזרת הקוסם הטוב","✨"), s(4,"normal","ספריית הקסמים","📚"),
      s(5,"normal","חדר הגחלים","🕯️"), s(6,"trap","שיעור נפל מרע","💀"),
      s(7,"normal","חדר הדיון","🦉"), s(8,"normal","גן הצמחי-קסם","🌿"),
      s(9,"bonus","מדרגות הקסם","🌀"), s(10,"normal","מגדל הכשפים","🗼"),
      s(11,"normal","חדר האמן","🎨"), s(12,"card","קסם ההאצה","⚡"),
      s(13,"normal","מעבדת הקסמים","⚗️"), s(14,"trap","קסם ההאטה","🐌"),
      s(15,"normal","גג הטיסה","🧹"), s(16,"normal","חדר הנשקים","🪄"),
      s(17,"card","ספר הקסמים העתיק","📖"), s(18,"normal","מרפסת הנשקפים","🌙"),
      s(19,"trap","כישוף הקיפאון","🧊"), s(20,"normal","המסדרון הסודי","🕵️"),
      s(21,"card","עזרת פיית הקסמים","🧚"), s(22,"normal","חדר הפורטלים","🌀"),
      s(23,"trap","כישוף ההחלפה","🔄"), s(24,"normal","אולם הבחינות","📝"),
      s(25,"card","ניצחון הקוסם","🌟"), s(26,"normal","מבחן האומץ","⚔️"),
      s(27,"bonus","ניסוי הטיסה","🦅"), s(28,"trap","כישוף ההשכחה","❓"),
      s(29,"normal","הרצאת הגדול","🎓"), s(30,"card","אות הכבוד","🏅"),
      s(31,"normal","מסדרון הפסל","🗿"), s(32,"trap","שבירת השרביט","💫"),
      s(33,"normal","שיעור הטיסה","🌙"), s(34,"card","שרביט הקסמים","🪄"),
      s(35,"trap","כישוף הנסיגה","🌀"), s(36,"win","אדון הקוסמים","🏆"),
    ],
    events: {
      card: [
        { title:"עזרת הקוסם הטוב", description:"קוסם מבוגר ומנוסה לחש לך קסם מהירות!", icon:"✨", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
        { title:"קסם ההאצה", description:"הצלחת לבצע קסם האצה מושלם — קדימה!", icon:"⚡", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
        { title:"ספר קסמים עתיק", description:"מצאת ספר קסמים סודי עם לחש קפיצה נדיר.", icon:"📖", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
        { title:"עזרת הפיה", description:"פיית קסמים קטנה עפה ולחשה לך מסלול קצר.", icon:"🧚", effectText:"התקדם 2 משבצות", effect:{type:"move",value:2} },
        { title:"ניצחון הקוסם", description:"פרצת את כל הניסויים — הדרך פתוחה לפניך!", icon:"🌟", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
        { title:"אות הכבוד", description:"קיבלת אות כבוד מהמועצה — הדרך מהירה יותר!", icon:"🏅", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
        { title:"שרביט חדש", description:"שרביט קסמים חזק התגלה ומאיץ את מסעך.", icon:"🪄", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
      ],
      trap: [
        { title:"כישוף נפל", description:"כישוף נפל של תלמיד רשע פגע בך ודחה אותך.", icon:"💀", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"קסם האטה", description:"נפלת על לחש האטה — זזת לאחור לאט.", icon:"🐌", effectText:"חזור 2 משבצות", effect:{type:"move",value:-2} },
        { title:"כישוף הקיפאון", description:"קסם קרח הקפיא אותך לרגע. נסוגת לאחור.", icon:"🧊", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"כישוף ההחלפה", description:"כישוף בלבול שלח אותך לכיוון הלא נכון.", icon:"🔄", effectText:"חזור 2 משבצות", effect:{type:"move",value:-2} },
        { title:"כישוף השכחה", description:"שכחת לאן ללכת! נסוגת לחפש את הכיוון.", icon:"❓", effectText:"חזור 4 משבצות", effect:{type:"move",value:-4} },
        { title:"שבירת שרביט", description:"השרביט נשבר ברגע קריטי. חייבים לחזור.", icon:"💫", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"כישוף הנסיגה", description:"כישוף עוין שלח אותך ישר לאחור בכוח.", icon:"🌀", effectText:"חזור 2 משבצות", effect:{type:"move",value:-2} },
      ],
      bonus: [
        { title:"מדרגות הקסם!", description:"מדרגות קסומות נעו לבד וקפצו אותך קדימה!", icon:"🌀", effectText:"התקדם 5 משבצות", effect:{type:"move",value:5} },
        { title:"ניסוי טיסה מוצלח!", description:"ניסוי הטיסה עלה יפה — עפת קדימה כמו ציפור!", icon:"🦅", effectText:"התקדם 5 משבצות", effect:{type:"move",value:5} },
      ],
    },
  },

  {
    id: "dragons",
    label: "🐉 מערות דרקון",
    title: "מערות הדרקון",
    subtitle: "חיפוש אוצר הדרקון",
    icon: "🐉",
    spaces: [
      s(1,"normal","כניסת המערה","🕳️"), s(2,"normal","מסדרון האפלה","🌑"),
      s(3,"card","תגלית הגביש","💎"), s(4,"normal","חדר האבנים","🪨"),
      s(5,"normal","ממלכת העטלפים","🦇"), s(6,"trap","ראש הדרקון הקטן","🐲"),
      s(7,"normal","נהר הלבה התת-ארצי","🔥"), s(8,"normal","מנהרת הרוחות","💨"),
      s(9,"bonus","חדר הקפיצה","🌟"), s(10,"normal","מרחב הסטלגמיט","🗿"),
      s(11,"normal","שביל הגביש","✨"), s(12,"card","אוצר הדרקון הקטן","💰"),
      s(13,"normal","מפל האבנים","💧"), s(14,"trap","שומר המסדרון","👾"),
      s(15,"normal","חדר הכבוד","🏛️"), s(16,"normal","מנהרת הסחרור","🌀"),
      s(17,"card","ידידות הדרקון","🤝"), s(18,"normal","שביל הפחם","⬛"),
      s(19,"trap","נשיפת אש","🔥"), s(20,"normal","שדה הגביש הכחול","💙"),
      s(21,"card","קסם הגביש","✨"), s(22,"normal","כיכר הדרקונים","🐉"),
      s(23,"trap","מלכודת האבנים","🪤"), s(24,"normal","מבוא האוצר","🚪"),
      s(25,"card","מפת האוצר","🗺️"), s(26,"normal","שמירת הדרקון","🛡️"),
      s(27,"bonus","מסלול הסוד","⭐"), s(28,"trap","נפילת מנהרה","💥"),
      s(29,"normal","חדר הדרקונים הישנים","😴"), s(30,"card","כנף הדרקון","🐲"),
      s(31,"normal","שביל הסוף","🛤️"), s(32,"trap","קרב הדרקון האחרון","⚔️"),
      s(33,"normal","פרוזדור הניצחון","🏆"), s(34,"card","ברכת הדרקון","🙏"),
      s(35,"trap","שומר האוצר הסופי","💀"), s(36,"win","חדר האוצר","🏆"),
    ],
    events: {
      card: [
        { title:"תגלית גביש", description:"מצאת גביש קסום שמאיר את הדרך ומאיץ אותך!", icon:"💎", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
        { title:"אוצר קטן", description:"מצאת אוצר קטן של דרקון צעיר — קדם להמשיך!", icon:"💰", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
        { title:"ידידות הדרקון", description:"דרקון ירוק קטן החליט להיות ידידך ועזר לך!", icon:"🤝", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
        { title:"קסם הגביש", description:"גביש כחול קסם לעצמו ושלח אותך קדימה.", icon:"✨", effectText:"התקדם 2 משבצות", effect:{type:"move",value:2} },
        { title:"מפת אוצר", description:"מצאת מפה ישנה עם קיצור דרך לחדר האוצר!", icon:"🗺️", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
        { title:"כנף הדרקון", description:"דרקון ידידותי נשא אותך על כנפיו קדימה!", icon:"🐲", effectText:"התקדם 3 משבצות", effect:{type:"move",value:3} },
        { title:"ברכת הדרקון", description:"דרקון עתיק בירך אותך — הדרך פתוחה!", icon:"🙏", effectText:"התקדם 4 משבצות", effect:{type:"move",value:4} },
      ],
      trap: [
        { title:"דרקון זעיר!", description:"דרקון קטן רדף אחריך ונאלצת לרוץ לאחור.", icon:"🐲", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"שומר מסדרון", description:"שומר ענקי חסם את הדרך — נסוג לחפש מעבר.", icon:"👾", effectText:"חזור 2 משבצות", effect:{type:"move",value:-2} },
        { title:"נשיפת אש", description:"דרקון נשף אש! ברחת לאחור בזריזות.", icon:"🔥", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"מלכודת אבנים", description:"אבנים נפלו וחסמו את הדרך. עקפת לאחור.", icon:"🪤", effectText:"חזור 4 משבצות", effect:{type:"move",value:-4} },
        { title:"נפילת מנהרה", description:"חלק מהמנהרה קרס! נסוגת מהר לאחור.", icon:"💥", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
        { title:"קרב דרקון", description:"דרקון גדול תקף — בקושי נמלטת לאחור!", icon:"⚔️", effectText:"חזור 2 משבצות", effect:{type:"move",value:-2} },
        { title:"שומר האוצר", description:"השומר הסופי עצר אותך! חייבים לחזור.", icon:"💀", effectText:"חזור 3 משבצות", effect:{type:"move",value:-3} },
      ],
      bonus: [
        { title:"מסלול סודי!", description:"מצאת מנהרה סודית שהדרקונים אף פעם לא מגלים!", icon:"⭐", effectText:"התקדם 5 משבצות", effect:{type:"move",value:5} },
        { title:"חדר הקפיצה!", description:"חדר מיוחד עם קפיץ ענק שיירה אותך קדימה!", icon:"🌟", effectText:"התקדם 5 משבצות", effect:{type:"move",value:5} },
      ],
    },
  },
];
